import type { TropeType } from "./trope";
import type { BookName } from "./PlayViewScreen";

export { audio } from "../data/audio/audioImports";

export const bookMap = {
  // Import Texts
  Amos: () => import("../data/torah/json/Amos.json"),
  Deuteronomy: () => import("../data/torah/json/Deuteronomy.json"),
  Exodus: () => import("../data/torah/json/Exodus.json"),
  Ezekiel: () => import("../data/torah/json/Ezekiel.json"),
  Genesis: () => import("../data/torah/json/Genesis.json"),
  Hosea: () => import("../data/torah/json/Hosea.json"),
  Isaiah: () => import("../data/torah/json/Isaiah.json"),
  Jeremiah: () => import("../data/torah/json/Jeremiah.json"),
  Joel: () => import("../data/torah/json/Joel.json"),
  Joshua: () => import("../data/torah/json/Joshua.json"),
  Judges: () => import("../data/torah/json/Judges.json"),
  "I Kings": () => import("../data/torah/json/Kings_1.json"),
  "II Kings": () => import("../data/torah/json/Kings_2.json"),
  Leviticus: () => import("../data/torah/json/Leviticus.json"),
  Malachi: () => import("../data/torah/json/Malachi.json"),
  Micah: () => import("../data/torah/json/Micah.json"),
  Numbers: () => import("../data/torah/json/Numbers.json"),
  Obadiah: () => import("../data/torah/json/Obadiah.json"),
  "I Samuel": () => import("../data/torah/json/Samuel_1.json"),
  "II Samuel": () => import("../data/torah/json/Samuel_2.json"),
  Zechariah: () => import("../data/torah/json/Zechariah.json"),
};

type Importer<T> = () => Promise<{ default: T }>;

export const transBookMap = {
  // Import Translations
  Genesis: () => import("../data/torah/translation/Genesis.json"),
  Exodus: () => import("../data/torah/translation/Exodus.json"),
  Deuteronomy: () => import("../data/torah/translation/Deuteronomy.json"),
  Leviticus: () => import("../data/torah/translation/Leviticus.json"),
  Numbers: () => import("../data/torah/translation/Numbers.json"),
  Isaiah: () => import("../data/torah/translation/Isaiah.json"),
  Joshua: () => import("../data/torah/translation/Joshua.json"),
  Judges: () => import("../data/torah/translation/Judges.json"),
  Malachi: () => import("../data/torah/translation/Malachi.json"),
  Obadiah: () => import("../data/torah/translation/Obadiah.json"),
  Micah: () => import("../data/torah/translation/Micah.json"),
  "I Samuel": () => import("../data/torah/translation/Samuel_1.json"),
  "II Samuel": () => import("../data/torah/translation/Samuel_2.json"),
  Zechariah: () => import("../data/torah/translation/Zechariah.json"),
  Joel: () => import("../data/torah/translation/Joel.json"),
  Jeremiah: () => import("../data/torah/translation/Jeremiah.json"),
  Hosea: () => import("../data/torah/translation/Hosea.json"),
  Ezekiel: () => import("../data/torah/translation/Ezekiel.json"),
  Amos: () => import("../data/torah/translation/Amos.json"),
  "II Kings": () => import("../data/torah/translation/Kings_2.json"),
  "I Kings": () => import("../data/torah/translation/Kings_1.json"),
};

export const labels: Record<BookName, Importer<Record<string, number[]>>> = {
  Amos: () => import("../data/torah/labels/Amos.json"),
  Deuteronomy: () => import("../data/torah/labels/Deuteronomy.json"),
  Exodus: () => import("../data/torah/labels/Exodus.json"),
  Ezekiel: () => import("../data/torah/labels/Ezekiel.json"),
  Genesis: () => import("../data/torah/labels/Genesis.json"),
  Hosea: () => import("../data/torah/labels/Hosea.json"),
  Isaiah: () => import("../data/torah/labels/Isaiah.json"),
  Jeremiah: () => import("../data/torah/labels/Jeremiah.json"),
  Joel: () => import("../data/torah/labels/Joel.json"),
  Joshua: () => import("../data/torah/labels/Joshua.json"),
  Judges: () => import("../data/torah/labels/Judges.json"),
  "I Kings": () => import("../data/torah/labels/I Kings.json"),
  "II Kings": () => import("../data/torah/labels/II Kings.json"),
  Leviticus: () => import("../data/torah/labels/Leviticus.json"),
  Malachi: () => import("../data/torah/labels/Malachi.json"),
  Micah: () => import("../data/torah/labels/Micah.json"),
  Numbers: () => import("../data/torah/labels/Numbers.json"),
  Obadiah: () => import("../data/torah/labels/Obadiah.json"),
  "I Samuel": () => import("../data/torah/labels/I Samuel.json"),
  "II Samuel": () => import("../data/torah/labels/II Samuel.json"),
  Zechariah: () => import("../data/torah/labels/Zechariah.json"),
};

export const hebFont = "Taamey Frank Taamim Fix";
export const tikkunFont = "Stam Ashkenaz CLM";
export const fonts = {
  [hebFont]: require("../fonts/TaameyFrank-taamim-fix.ttf"),
  [tikkunFont]: require("../fonts/stamashkenazclm-webfont.ttf"),
};

export const tropeAudio: { [k in TropeType]: { [i: number]: any } } = {
  torah: {
    1: require("../data/trope/audio/torah-1.mp3"),
    2: require("../data/trope/audio/torah-2.mp3"),
    3: require("../data/trope/audio/torah-3.mp3"),
    4: require("../data/trope/audio/torah-4.mp3"),
    5: require("../data/trope/audio/torah-5.mp3"),
    6: require("../data/trope/audio/torah-6.mp3"),
    7: require("../data/trope/audio/torah-7.mp3"),
    8: require("../data/trope/audio/torah-8.mp3"),
    9: require("../data/trope/audio/torah-9.mp3"),
    10: require("../data/trope/audio/torah-10.mp3"),
    11: require("../data/trope/audio/torah-11.mp3"),
    12: require("../data/trope/audio/torah-12.mp3"),
  },
  haftarah: {
    1: require("../data/trope/audio/haftarah-1.mp3"),
    2: require("../data/trope/audio/haftarah-2.mp3"),
    3: require("../data/trope/audio/haftarah-3.mp3"),
    4: require("../data/trope/audio/haftarah-4.mp3"),
    5: require("../data/trope/audio/haftarah-5.mp3"),
    6: require("../data/trope/audio/haftarah-6.mp3"),
    7: require("../data/trope/audio/haftarah-7.mp3"),
    8: require("../data/trope/audio/haftarah-8.mp3"),
    9: require("../data/trope/audio/haftarah-9.mp3"),
    10: require("../data/trope/audio/haftarah-10.mp3"),
    11: require("../data/trope/audio/haftarah-11.mp3"),
    12: require("../data/trope/audio/haftarah-12.mp3"),
    13: require("../data/trope/audio/haftarah-13.mp3"),
    14: require("../data/trope/audio/haftarah-14.mp3"),
    15: require("../data/trope/audio/haftarah-15.mp3"),
  },
  esther: {
    1: require("../data/trope/audio/esther-1.mp3"),
    2: require("../data/trope/audio/esther-2.mp3"),
    3: require("../data/trope/audio/esther-3.mp3"),
    4: require("../data/trope/audio/esther-4.mp3"),
    5: require("../data/trope/audio/esther-5.mp3"),
    6: require("../data/trope/audio/esther-6.mp3"),
    7: require("../data/trope/audio/esther-7.mp3"),
    8: require("../data/trope/audio/esther-8.mp3"),
    9: require("../data/trope/audio/esther-9.mp3"),
    10: require("../data/trope/audio/esther-10.mp3"),
    11: require("../data/trope/audio/esther-11.mp3"),
    12: require("../data/trope/audio/esther-12.mp3"),
    13: require("../data/trope/audio/esther-13.mp3"),
    14: require("../data/trope/audio/esther-14.mp3"),
    15: require("../data/trope/audio/esther-15.mp3"),
    16: require("../data/trope/audio/esther-16.mp3"),
  },
  eicha: {
    1: require("../data/trope/audio/eicha-1.mp3"),
    2: require("../data/trope/audio/eicha-2.mp3"),
    3: require("../data/trope/audio/eicha-3.mp3"),
    4: require("../data/trope/audio/eicha-4.mp3"),
    5: require("../data/trope/audio/eicha-5.mp3"),
    6: require("../data/trope/audio/eicha-6.mp3"),
    7: require("../data/trope/audio/eicha-7.mp3"),
    8: require("../data/trope/audio/eicha-8.mp3"),
    9: require("../data/trope/audio/eicha-9.mp3"),
    10: require("../data/trope/audio/eicha-10.mp3"),
    11: require("../data/trope/audio/eicha-11.mp3"),
    12: require("../data/trope/audio/eicha-12.mp3"),
  },
  "3megillot": {
    1: require("../data/trope/audio/3megillot-1.mp3"),
    2: require("../data/trope/audio/3megillot-2.mp3"),
    3: require("../data/trope/audio/3megillot-3.mp3"),
    4: require("../data/trope/audio/3megillot-4.mp3"),
    5: require("../data/trope/audio/3megillot-5.mp3"),
    6: require("../data/trope/audio/3megillot-6.mp3"),
    7: require("../data/trope/audio/3megillot-7.mp3"),
    8: require("../data/trope/audio/3megillot-8.mp3"),
    9: require("../data/trope/audio/3megillot-9.mp3"),
    10: require("../data/trope/audio/3megillot-10.mp3"),
    11: require("../data/trope/audio/3megillot-11.mp3"),
    12: require("../data/trope/audio/3megillot-12.mp3"),
    13: require("../data/trope/audio/3megillot-13.mp3"),
    14: require("../data/trope/audio/3megillot-14.mp3"),
  },
  hhd: {
    1: require("../data/trope/audio/hhd-1.mp3"),
    2: require("../data/trope/audio/hhd-2.mp3"),
    3: require("../data/trope/audio/hhd-3.mp3"),
    4: require("../data/trope/audio/hhd-4.mp3"),
    5: require("../data/trope/audio/hhd-5.mp3"),
    6: require("../data/trope/audio/hhd-6.mp3"),
    7: require("../data/trope/audio/hhd-7.mp3"),
    8: require("../data/trope/audio/hhd-8.mp3"),
    9: require("../data/trope/audio/hhd-9.mp3"),
    10: require("../data/trope/audio/hhd-10.mp3"),
    11: require("../data/trope/audio/hhd-11.mp3"),
    12: require("../data/trope/audio/hhd-12.mp3"),
    13: require("../data/trope/audio/hhd-13.mp3"),
    14: require("../data/trope/audio/hhd-14.mp3"),
  },
};

export const tropeXml: { [k in TropeType]: { [i: number]: any } } = {
  torah: {
    1: require("../data/trope/text/torah-1.xml"),
    2: require("../data/trope/text/torah-2.xml"),
    3: require("../data/trope/text/torah-3.xml"),
    4: require("../data/trope/text/torah-4.xml"),
    5: require("../data/trope/text/torah-5.xml"),
    6: require("../data/trope/text/torah-6.xml"),
    7: require("../data/trope/text/torah-7.xml"),
    8: require("../data/trope/text/torah-8.xml"),
    9: require("../data/trope/text/torah-9.xml"),
    10: require("../data/trope/text/torah-10.xml"),
    11: require("../data/trope/text/torah-11.xml"),
    12: require("../data/trope/text/torah-12.xml"),
  },
  haftarah: {
    1: require("../data/trope/text/haftarah-1.xml"),
    2: require("../data/trope/text/haftarah-2.xml"),
    3: require("../data/trope/text/haftarah-3.xml"),
    4: require("../data/trope/text/haftarah-4.xml"),
    5: require("../data/trope/text/haftarah-5.xml"),
    6: require("../data/trope/text/haftarah-6.xml"),
    7: require("../data/trope/text/haftarah-7.xml"),
    8: require("../data/trope/text/haftarah-8.xml"),
    9: require("../data/trope/text/haftarah-9.xml"),
    10: require("../data/trope/text/haftarah-10.xml"),
    11: require("../data/trope/text/haftarah-11.xml"),
    12: require("../data/trope/text/haftarah-12.xml"),
    13: require("../data/trope/text/haftarah-13.xml"),
    14: require("../data/trope/text/haftarah-14.xml"),
    15: require("../data/trope/text/haftarah-15.xml"),
  },
  esther: {
    1: require("../data/trope/text/esther-1.xml"),
    2: require("../data/trope/text/esther-2.xml"),
    3: require("../data/trope/text/esther-3.xml"),
    4: require("../data/trope/text/esther-4.xml"),
    5: require("../data/trope/text/esther-5.xml"),
    6: require("../data/trope/text/esther-6.xml"),
    7: require("../data/trope/text/esther-7.xml"),
    8: require("../data/trope/text/esther-8.xml"),
    9: require("../data/trope/text/esther-9.xml"),
    10: require("../data/trope/text/esther-10.xml"),
    11: require("../data/trope/text/esther-11.xml"),
    12: require("../data/trope/text/esther-12.xml"),
    13: require("../data/trope/text/esther-13.xml"),
    14: require("../data/trope/text/esther-14.xml"),
    15: require("../data/trope/text/esther-15.xml"),
    16: require("../data/trope/text/esther-16.xml"),
  },
  eicha: {
    1: require("../data/trope/text/eicha-1.xml"),
    2: require("../data/trope/text/eicha-2.xml"),
    3: require("../data/trope/text/eicha-3.xml"),
    4: require("../data/trope/text/eicha-4.xml"),
    5: require("../data/trope/text/eicha-5.xml"),
    6: require("../data/trope/text/eicha-6.xml"),
    7: require("../data/trope/text/eicha-7.xml"),
    8: require("../data/trope/text/eicha-8.xml"),
    9: require("../data/trope/text/eicha-9.xml"),
    10: require("../data/trope/text/eicha-10.xml"),
    11: require("../data/trope/text/eicha-11.xml"),
    12: require("../data/trope/text/eicha-12.xml"),
  },
  "3megillot": {
    1: require("../data/trope/text/3megillot-1.xml"),
    2: require("../data/trope/text/3megillot-2.xml"),
    3: require("../data/trope/text/3megillot-3.xml"),
    4: require("../data/trope/text/3megillot-4.xml"),
    5: require("../data/trope/text/3megillot-5.xml"),
    6: require("../data/trope/text/3megillot-6.xml"),
    7: require("../data/trope/text/3megillot-7.xml"),
    8: require("../data/trope/text/3megillot-8.xml"),
    9: require("../data/trope/text/3megillot-9.xml"),
    10: require("../data/trope/text/3megillot-10.xml"),
    11: require("../data/trope/text/3megillot-11.xml"),
    12: require("../data/trope/text/3megillot-12.xml"),
    13: require("../data/trope/text/3megillot-13.xml"),
    14: require("../data/trope/text/3megillot-14.xml"),
  },
  hhd: {
    1: require("../data/trope/text/hhd-1.xml"),
    2: require("../data/trope/text/hhd-2.xml"),
    3: require("../data/trope/text/hhd-3.xml"),
    4: require("../data/trope/text/hhd-4.xml"),
    5: require("../data/trope/text/hhd-5.xml"),
    6: require("../data/trope/text/hhd-6.xml"),
    7: require("../data/trope/text/hhd-7.xml"),
    8: require("../data/trope/text/hhd-8.xml"),
    9: require("../data/trope/text/hhd-9.xml"),
    10: require("../data/trope/text/hhd-10.xml"),
    11: require("../data/trope/text/hhd-11.xml"),
    12: require("../data/trope/text/hhd-12.xml"),
    13: require("../data/trope/text/hhd-13.xml"),
    14: require("../data/trope/text/hhd-14.xml"),
  },
};

export const tropeLabels = {
  torah: require("../data/trope/labels/torah.json"),
  haftarah: require("../data/trope/labels/haftarah.json"),
  esther: require("../data/trope/labels/esther.json"),
  eicha: require("../data/trope/labels/eicha.json"),
  "3megillot": require("../data/trope/labels/3megillot.json"),
  hhd: require("../data/trope/labels/hhd.json"),
};
