import type { TropeType } from "./trope";

export const bookMap = {
  // Import Texts
  Amos: () => import("../data/torah/json/Amos.json"),
  Deuteronomy: () => import("../data/torah/json/Deuteronomy.json"),
  Exodus: () => import("../data/torah/json/Exodus.json"),
  Ezekiel: () => import("../data/torah/json/Ezekiel.json"),
  Genesis: () => import("../data/torah/json/Genesis.json"),
  Hosea: () => import("../data/torah/json/Hosea.json"),
  Isaiah: () => import("../data/torah/json/Isaiah.json"),
  Jeremiah: () => import("../data/torah/json/Jeremiah.json"),
  Joel: () => import("../data/torah/json/Joel.json"),
  Joshua: () => import("../data/torah/json/Joshua.json"),
  Judges: () => import("../data/torah/json/Judges.json"),
  "I Kings": () => import("../data/torah/json/Kings_1.json"),
  "II Kings": () => import("../data/torah/json/Kings_2.json"),
  Leviticus: () => import("../data/torah/json/Leviticus.json"),
  Malachi: () => import("../data/torah/json/Malachi.json"),
  Micah: () => import("../data/torah/json/Micah.json"),
  Numbers: () => import("../data/torah/json/Numbers.json"),
  Obadiah: () => import("../data/torah/json/Obadiah.json"),
  "I Samuel": () => import("../data/torah/json/Samuel_1.json"),
  "II Samuel": () => import("../data/torah/json/Samuel_2.json"),
  Zechariah: () => import("../data/torah/json/Zechariah.json"),
};

export const transBookMap = {
  // Import Translations
  Genesis: () => import("../data/torah/translation/Genesis.json"),
  Exodus: () => import("../data/torah/translation/Exodus.json"),
  Deuteronomy: () => import("../data/torah/translation/Deuteronomy.json"),
  Leviticus: () => import("../data/torah/translation/Leviticus.json"),
  Numbers: () => import("../data/torah/translation/Numbers.json"),
  Isaiah: () => import("../data/torah/translation/Isaiah.json"),
  Joshua: () => import("../data/torah/translation/Joshua.json"),
  Judges: () => import("../data/torah/translation/Judges.json"),
  Malachi: () => import("../data/torah/translation/Malachi.json"),
  Obadiah: () => import("../data/torah/translation/Obadiah.json"),
  Micah: () => import("../data/torah/translation/Micah.json"),
  "I Samuel": () => import("../data/torah/translation/Samuel_1.json"),
  "II Samuel": () => import("../data/torah/translation/Samuel_2.json"),
  Zechariah: () => import("../data/torah/translation/Zechariah.json"),
  Joel: () => import("../data/torah/translation/Joel.json"),
  Jeremiah: () => import("../data/torah/translation/Jeremiah.json"),
  Hosea: () => import("../data/torah/translation/Hosea.json"),
  Ezekiel: () => import("../data/torah/translation/Ezekiel.json"),
  Amos: () => import("../data/torah/translation/Amos.json"),
  "II Kings": () => import("../data/torah/translation/Kings_2.json"),
  "I Kings": () => import("../data/torah/translation/Kings_1.json"),
};

export const labels = {
  Genesis: () => import("../data/torah/labels/Genesis.json"),
  Exodus: () => import("../data/torah/labels/Exodus.json"),
  Leviticus: () => import("../data/torah/labels/Leviticus.json"),
  Numbers: () => import("../data/torah/labels/Numbers.json"),
  Deuteronomy: () => import("../data/torah/labels/Deuteronomy.json"),
};

export const audio = {
  Bereshit: {
    1: require("../data/audio/Bereshit-1.mp3"),
    2: require("../data/audio/Bereshit-2.mp3"),
    3: require("../data/audio/Bereshit-3.mp3"),
    4: require("../data/audio/Bereshit-4.mp3"),
    5: require("../data/audio/Bereshit-5.mp3"),
    6: require("../data/audio/Bereshit-6.mp3"),
    7: require("../data/audio/Bereshit-7.mp3"),
    H: require("../data/audio/Bereshit-H.mp3"),
  },
  Noach: {
    1: require("../data/audio/Noach-1.mp3"),
    2: require("../data/audio/Noach-2.mp3"),
    3: require("../data/audio/Noach-3.mp3"),
    4: require("../data/audio/Noach-4.mp3"),
    5: require("../data/audio/Noach-5.mp3"),
    6: require("../data/audio/Noach-6.mp3"),
    7: require("../data/audio/Noach-7.mp3"),
    H: require("../data/audio/Noach-H.mp3"),
  },
  "Lech-Lecha": {
    1: require("../data/audio/Lech-Lecha-1.mp3"),
    2: require("../data/audio/Lech-Lecha-2.mp3"),
    3: require("../data/audio/Lech-Lecha-3.mp3"),
    4: require("../data/audio/Lech-Lecha-4.mp3"),
    5: require("../data/audio/Lech-Lecha-5.mp3"),
    6: require("../data/audio/Lech-Lecha-6.mp3"),
    7: require("../data/audio/Lech-Lecha-7.mp3"),
    H: require("../data/audio/Lech-Lecha-H.mp3"),
  },
  Vayera: {
    1: require("../data/audio/Vayera-1.mp3"),
    2: require("../data/audio/Vayera-2.mp3"),
    3: require("../data/audio/Vayera-3.mp3"),
    4: require("../data/audio/Vayera-4.mp3"),
    5: require("../data/audio/Vayera-5.mp3"),
    6: require("../data/audio/Vayera-6.mp3"),
    7: require("../data/audio/Vayera-7.mp3"),
    H: require("../data/audio/Vayera-H.mp3"),
  },
  "Chayei Sara": {
    1: require("../data/audio/ChayeiSara-1.mp3"),
    2: require("../data/audio/ChayeiSara-2.mp3"),
    3: require("../data/audio/ChayeiSara-3.mp3"),
    4: require("../data/audio/ChayeiSara-4.mp3"),
    5: require("../data/audio/ChayeiSara-5.mp3"),
    6: require("../data/audio/ChayeiSara-6.mp3"),
    7: require("../data/audio/ChayeiSara-7.mp3"),
    H: require("../data/audio/ChayeiSara-H.mp3"),
  },
  Toldot: {
    1: require("../data/audio/Toldot-1.mp3"),
    2: require("../data/audio/Toldot-2.mp3"),
    3: require("../data/audio/Toldot-3.mp3"),
    4: require("../data/audio/Toldot-4.mp3"),
    5: require("../data/audio/Toldot-5.mp3"),
    6: require("../data/audio/Toldot-6.mp3"),
    7: require("../data/audio/Toldot-7.mp3"),
    H: require("../data/audio/Toldot-H.mp3"),
  },
  Vayetzei: {
    1: require("../data/audio/Vayetzei-1.mp3"),
    2: require("../data/audio/Vayetzei-2.mp3"),
    3: require("../data/audio/Vayetzei-3.mp3"),
    4: require("../data/audio/Vayetzei-4.mp3"),
    5: require("../data/audio/Vayetzei-5.mp3"),
    6: require("../data/audio/Vayetzei-6.mp3"),
    7: require("../data/audio/Vayetzei-7.mp3"),
    H: require("../data/audio/Vayetzei-H.mp3"),
  },
  Vayishlach: {
    1: require("../data/audio/Vayishlach-1.mp3"),
    2: require("../data/audio/Vayishlach-2.mp3"),
    3: require("../data/audio/Vayishlach-3.mp3"),
    4: require("../data/audio/Vayishlach-4.mp3"),
    5: require("../data/audio/Vayishlach-5.mp3"),
    6: require("../data/audio/Vayishlach-6.mp3"),
    7: require("../data/audio/Vayishlach-7.mp3"),
    H: require("../data/audio/Vayishlach-H.mp3"),
  },
  Vayeshev: {
    1: require("../data/audio/Vayeshev-1.mp3"),
    2: require("../data/audio/Vayeshev-2.mp3"),
    3: require("../data/audio/Vayeshev-3.mp3"),
    4: require("../data/audio/Vayeshev-4.mp3"),
    5: require("../data/audio/Vayeshev-5.mp3"),
    6: require("../data/audio/Vayeshev-6.mp3"),
    7: require("../data/audio/Vayeshev-7.mp3"),
    H: require("../data/audio/Vayeshev-H.mp3"),
  },
  Miketz: {
    1: require("../data/audio/Miketz-1.mp3"),
    2: require("../data/audio/Miketz-2.mp3"),
    3: require("../data/audio/Miketz-3.mp3"),
    4: require("../data/audio/Miketz-4.mp3"),
    5: require("../data/audio/Miketz-5.mp3"),
    6: require("../data/audio/Miketz-6.mp3"),
    7: require("../data/audio/Miketz-7.mp3"),
    H: require("../data/audio/Miketz-H.mp3"),
  },
  Vayigash: {
    1: require("../data/audio/Vayigash-1.mp3"),
    2: require("../data/audio/Vayigash-2.mp3"),
    3: require("../data/audio/Vayigash-3.mp3"),
    4: require("../data/audio/Vayigash-4.mp3"),
    5: require("../data/audio/Vayigash-5.mp3"),
    6: require("../data/audio/Vayigash-6.mp3"),
    7: require("../data/audio/Vayigash-7.mp3"),
    H: require("../data/audio/Vayigash-H.mp3"),
  },
  Vayechi: {
    1: require("../data/audio/Vayechi-1.mp3"),
    2: require("../data/audio/Vayechi-2.mp3"),
    3: require("../data/audio/Vayechi-3.mp3"),
    4: require("../data/audio/Vayechi-4.mp3"),
    5: require("../data/audio/Vayechi-5.mp3"),
    6: require("../data/audio/Vayechi-6.mp3"),
    7: require("../data/audio/Vayechi-7.mp3"),
    H: require("../data/audio/Vayechi-H.mp3"),
  },
  Shemot: {
    1: require("../data/audio/Shemot-1.mp3"),
    2: require("../data/audio/Shemot-2.mp3"),
    3: require("../data/audio/Shemot-3.mp3"),
    4: require("../data/audio/Shemot-4.mp3"),
    5: require("../data/audio/Shemot-5.mp3"),
    6: require("../data/audio/Shemot-6.mp3"),
    7: require("../data/audio/Shemot-7.mp3"),
    H: require("../data/audio/Shemot-H.mp3"),
  },
  Vaera: {
    1: require("../data/audio/Vaera-1.mp3"),
    2: require("../data/audio/Vaera-2.mp3"),
    3: require("../data/audio/Vaera-3.mp3"),
    4: require("../data/audio/Vaera-4.mp3"),
    5: require("../data/audio/Vaera-5.mp3"),
    6: require("../data/audio/Vaera-6.mp3"),
    7: require("../data/audio/Vaera-7.mp3"),
    H: require("../data/audio/Vaera-H.mp3"),
  },
  Bo: {
    1: require("../data/audio/Bo-1.mp3"),
    2: require("../data/audio/Bo-2.mp3"),
    3: require("../data/audio/Bo-3.mp3"),
    4: require("../data/audio/Bo-4.mp3"),
    5: require("../data/audio/Bo-5.mp3"),
    6: require("../data/audio/Bo-6.mp3"),
    7: require("../data/audio/Bo-7.mp3"),
    H: require("../data/audio/Bo-H.mp3"),
  },
  Beshalach: {
    1: require("../data/audio/Beshalach-1.mp3"),
    2: require("../data/audio/Beshalach-2.mp3"),
    3: require("../data/audio/Beshalach-3.mp3"),
    4: require("../data/audio/Beshalach-4.mp3"),
    5: require("../data/audio/Beshalach-5.mp3"),
    6: require("../data/audio/Beshalach-6.mp3"),
    7: require("../data/audio/Beshalach-7.mp3"),
    H: require("../data/audio/Beshalach-H.mp3"),
  },
  Yitro: {
    1: require("../data/audio/Yitro-1.mp3"),
    2: require("../data/audio/Yitro-2.mp3"),
    3: require("../data/audio/Yitro-3.mp3"),
    4: require("../data/audio/Yitro-4.mp3"),
    5: require("../data/audio/Yitro-5.mp3"),
    6: require("../data/audio/Yitro-6.mp3"),
    7: require("../data/audio/Yitro-7.mp3"),
    H: require("../data/audio/Yitro-H.mp3"),
  },
  Mishpatim: {
    1: require("../data/audio/Mishpatim-1.mp3"),
    2: require("../data/audio/Mishpatim-2.mp3"),
    3: require("../data/audio/Mishpatim-3.mp3"),
    4: require("../data/audio/Mishpatim-4.mp3"),
    5: require("../data/audio/Mishpatim-5.mp3"),
    6: require("../data/audio/Mishpatim-6.mp3"),
    7: require("../data/audio/Mishpatim-7.mp3"),
    H: require("../data/audio/Mishpatim-H.mp3"),
  },
  Terumah: {
    1: require("../data/audio/Terumah-1.mp3"),
    2: require("../data/audio/Terumah-2.mp3"),
    3: require("../data/audio/Terumah-3.mp3"),
    4: require("../data/audio/Terumah-4.mp3"),
    5: require("../data/audio/Terumah-5.mp3"),
    6: require("../data/audio/Terumah-6.mp3"),
    7: require("../data/audio/Terumah-7.mp3"),
    H: require("../data/audio/Terumah-H.mp3"),
  },
  Tetzaveh: {
    1: require("../data/audio/Tetzaveh-1.mp3"),
    2: require("../data/audio/Tetzaveh-2.mp3"),
    3: require("../data/audio/Tetzaveh-3.mp3"),
    4: require("../data/audio/Tetzaveh-4.mp3"),
    5: require("../data/audio/Tetzaveh-5.mp3"),
    6: require("../data/audio/Tetzaveh-6.mp3"),
    7: require("../data/audio/Tetzaveh-7.mp3"),
    H: require("../data/audio/Tetzaveh-H.mp3"),
  },
  "Ki Tisa": {
    1: require("../data/audio/KiTisa-1.mp3"),
    2: require("../data/audio/KiTisa-2.mp3"),
    3: require("../data/audio/KiTisa-3.mp3"),
    4: require("../data/audio/KiTisa-4.mp3"),
    5: require("../data/audio/KiTisa-5.mp3"),
    6: require("../data/audio/KiTisa-6.mp3"),
    7: require("../data/audio/KiTisa-7.mp3"),
    H: require("../data/audio/KiTisa-H.mp3"),
  },
  Vayakhel: {
    1: require("../data/audio/Vayakhel-1.mp3"),
    2: require("../data/audio/Vayakhel-2.mp3"),
    3: require("../data/audio/Vayakhel-3.mp3"),
    4: require("../data/audio/Vayakhel-4.mp3"),
    5: require("../data/audio/Vayakhel-5.mp3"),
    6: require("../data/audio/Vayakhel-6.mp3"),
    7: require("../data/audio/Vayakhel-7.mp3"),
    H: require("../data/audio/Vayakhel-H.mp3"),
  },
  Pekudei: {
    1: require("../data/audio/Pekudei-1.mp3"),
    2: require("../data/audio/Pekudei-2.mp3"),
    3: require("../data/audio/Pekudei-3.mp3"),
    4: require("../data/audio/Pekudei-4.mp3"),
    5: require("../data/audio/Pekudei-5.mp3"),
    6: require("../data/audio/Pekudei-6.mp3"),
    7: require("../data/audio/Pekudei-7.mp3"),
    H: require("../data/audio/Pekudei-H.mp3"),
  },
  Vayikra: {
    1: require("../data/audio/Vayikra-1.mp3"),
    2: require("../data/audio/Vayikra-2.mp3"),
    3: require("../data/audio/Vayikra-3.mp3"),
    4: require("../data/audio/Vayikra-4.mp3"),
    5: require("../data/audio/Vayikra-5.mp3"),
    6: require("../data/audio/Vayikra-6.mp3"),
    7: require("../data/audio/Vayikra-7.mp3"),
    H: require("../data/audio/Vayikra-H.mp3"),
  },
  Tzav: {
    1: require("../data/audio/Tzav-1.mp3"),
    2: require("../data/audio/Tzav-2.mp3"),
    3: require("../data/audio/Tzav-3.mp3"),
    4: require("../data/audio/Tzav-4.mp3"),
    5: require("../data/audio/Tzav-5.mp3"),
    6: require("../data/audio/Tzav-6.mp3"),
    7: require("../data/audio/Tzav-7.mp3"),
    H: require("../data/audio/Tzav-H.mp3"),
  },
  Shmini: {
    1: require("../data/audio/Shmini-1.mp3"),
    2: require("../data/audio/Shmini-2.mp3"),
    3: require("../data/audio/Shmini-3.mp3"),
    4: require("../data/audio/Shmini-4.mp3"),
    5: require("../data/audio/Shmini-5.mp3"),
    6: require("../data/audio/Shmini-6.mp3"),
    7: require("../data/audio/Shmini-7.mp3"),
    H: require("../data/audio/Shmini-H.mp3"),
  },
  Tazria: {
    1: require("../data/audio/Tazria-1.mp3"),
    2: require("../data/audio/Tazria-2.mp3"),
    3: require("../data/audio/Tazria-3.mp3"),
    4: require("../data/audio/Tazria-4.mp3"),
    5: require("../data/audio/Tazria-5.mp3"),
    6: require("../data/audio/Tazria-6.mp3"),
    7: require("../data/audio/Tazria-7.mp3"),
    H: require("../data/audio/Tazria-H.mp3"),
  },
  Metzora: {
    1: require("../data/audio/Metzora-1.mp3"),
    2: require("../data/audio/Metzora-2.mp3"),
    3: require("../data/audio/Metzora-3.mp3"),
    4: require("../data/audio/Metzora-4.mp3"),
    5: require("../data/audio/Metzora-5.mp3"),
    6: require("../data/audio/Metzora-6.mp3"),
    7: require("../data/audio/Metzora-7.mp3"),
    H: require("../data/audio/Metzora-H.mp3"),
  },
  "Achrei Mot": {
    1: require("../data/audio/AchreiMot-1.mp3"),
    2: require("../data/audio/AchreiMot-2.mp3"),
    3: require("../data/audio/AchreiMot-3.mp3"),
    4: require("../data/audio/AchreiMot-4.mp3"),
    5: require("../data/audio/AchreiMot-5.mp3"),
    6: require("../data/audio/AchreiMot-6.mp3"),
    7: require("../data/audio/AchreiMot-7.mp3"),
    H: require("../data/audio/AchreiMot-H.mp3"),
  },
  Kedoshim: {
    1: require("../data/audio/Kedoshim-1.mp3"),
    2: require("../data/audio/Kedoshim-2.mp3"),
    3: require("../data/audio/Kedoshim-3.mp3"),
    4: require("../data/audio/Kedoshim-4.mp3"),
    5: require("../data/audio/Kedoshim-5.mp3"),
    6: require("../data/audio/Kedoshim-6.mp3"),
    7: require("../data/audio/Kedoshim-7.mp3"),
    H: require("../data/audio/Kedoshim-H.mp3"),
  },
  Emor: {
    1: require("../data/audio/Emor-1.mp3"),
    2: require("../data/audio/Emor-2.mp3"),
    3: require("../data/audio/Emor-3.mp3"),
    4: require("../data/audio/Emor-4.mp3"),
    5: require("../data/audio/Emor-5.mp3"),
    6: require("../data/audio/Emor-6.mp3"),
    7: require("../data/audio/Emor-7.mp3"),
    H: require("../data/audio/Emor-H.mp3"),
  },
  Behar: {
    1: require("../data/audio/Behar-1.mp3"),
    2: require("../data/audio/Behar-2.mp3"),
    3: require("../data/audio/Behar-3.mp3"),
    4: require("../data/audio/Behar-4.mp3"),
    5: require("../data/audio/Behar-5.mp3"),
    6: require("../data/audio/Behar-6.mp3"),
    7: require("../data/audio/Behar-7.mp3"),
    H: require("../data/audio/Behar-H.mp3"),
  },
  Bechukotai: {
    1: require("../data/audio/Bechukotai-1.mp3"),
    2: require("../data/audio/Bechukotai-2.mp3"),
    3: require("../data/audio/Bechukotai-3.mp3"),
    4: require("../data/audio/Bechukotai-4.mp3"),
    5: require("../data/audio/Bechukotai-5.mp3"),
    6: require("../data/audio/Bechukotai-6.mp3"),
    7: require("../data/audio/Bechukotai-7.mp3"),
    H: require("../data/audio/Bechukotai-H.mp3"),
  },
  Bamidbar: {
    1: require("../data/audio/Bamidbar-1.mp3"),
    2: require("../data/audio/Bamidbar-2.mp3"),
    3: require("../data/audio/Bamidbar-3.mp3"),
    4: require("../data/audio/Bamidbar-4.mp3"),
    5: require("../data/audio/Bamidbar-5.mp3"),
    6: require("../data/audio/Bamidbar-6.mp3"),
    7: require("../data/audio/Bamidbar-7.mp3"),
    H: require("../data/audio/Bamidbar-H.mp3"),
  },
  Nasso: {
    1: require("../data/audio/Nasso-1.mp3"),
    2: require("../data/audio/Nasso-2.mp3"),
    3: require("../data/audio/Nasso-3.mp3"),
    4: require("../data/audio/Nasso-4.mp3"),
    5: require("../data/audio/Nasso-5.mp3"),
    6: require("../data/audio/Nasso-6.mp3"),
    7: require("../data/audio/Nasso-7.mp3"),
    H: require("../data/audio/Nasso-H.mp3"),
  },
  "Beha'alotcha": {
    1: require("../data/audio/Behaalotcha-1.mp3"),
    2: require("../data/audio/Behaalotcha-2.mp3"),
    3: require("../data/audio/Behaalotcha-3.mp3"),
    4: require("../data/audio/Behaalotcha-4.mp3"),
    5: require("../data/audio/Behaalotcha-5.mp3"),
    6: require("../data/audio/Behaalotcha-6.mp3"),
    7: require("../data/audio/Behaalotcha-7.mp3"),
    H: require("../data/audio/Behaalotcha-H.mp3"),
  },
  "Sh'lach": {
    1: require("../data/audio/Shlach-1.mp3"),
    2: require("../data/audio/Shlach-2.mp3"),
    3: require("../data/audio/Shlach-3.mp3"),
    4: require("../data/audio/Shlach-4.mp3"),
    5: require("../data/audio/Shlach-5.mp3"),
    6: require("../data/audio/Shlach-6.mp3"),
    7: require("../data/audio/Shlach-7.mp3"),
    H: require("../data/audio/Shlach-H.mp3"),
  },
  Korach: {
    1: require("../data/audio/Korach-1.mp3"),
    2: require("../data/audio/Korach-2.mp3"),
    3: require("../data/audio/Korach-3.mp3"),
    4: require("../data/audio/Korach-4.mp3"),
    5: require("../data/audio/Korach-5.mp3"),
    6: require("../data/audio/Korach-6.mp3"),
    7: require("../data/audio/Korach-7.mp3"),
    H: require("../data/audio/Korach-H.mp3"),
  },
  Chukat: {
    1: require("../data/audio/Chukat-1.mp3"),
    2: require("../data/audio/Chukat-2.mp3"),
    3: require("../data/audio/Chukat-3.mp3"),
    4: require("../data/audio/Chukat-4.mp3"),
    5: require("../data/audio/Chukat-5.mp3"),
    6: require("../data/audio/Chukat-6.mp3"),
    7: require("../data/audio/Chukat-7.mp3"),
    H: require("../data/audio/Chukat-H.mp3"),
  },
  Balak: {
    1: require("../data/audio/Balak-1.mp3"),
    2: require("../data/audio/Balak-2.mp3"),
    3: require("../data/audio/Balak-3.mp3"),
    4: require("../data/audio/Balak-4.mp3"),
    5: require("../data/audio/Balak-5.mp3"),
    6: require("../data/audio/Balak-6.mp3"),
    7: require("../data/audio/Balak-7.mp3"),
    H: require("../data/audio/Balak-H.mp3"),
  },
  Pinchas: {
    1: require("../data/audio/Pinchas-1.mp3"),
    2: require("../data/audio/Pinchas-2.mp3"),
    3: require("../data/audio/Pinchas-3.mp3"),
    4: require("../data/audio/Pinchas-4.mp3"),
    5: require("../data/audio/Pinchas-5.mp3"),
    6: require("../data/audio/Pinchas-6.mp3"),
    7: require("../data/audio/Pinchas-7.mp3"),
    H: require("../data/audio/Pinchas-H.mp3"),
  },
  Matot: {
    1: require("../data/audio/Matot-1.mp3"),
    2: require("../data/audio/Matot-2.mp3"),
    3: require("../data/audio/Matot-3.mp3"),
    4: require("../data/audio/Matot-4.mp3"),
    5: require("../data/audio/Matot-5.mp3"),
    6: require("../data/audio/Matot-6.mp3"),
    7: require("../data/audio/Matot-7.mp3"),
    H: require("../data/audio/Matot-H.mp3"),
  },
  Masei: {
    1: require("../data/audio/Masei-1.mp3"),
    2: require("../data/audio/Masei-2.mp3"),
    3: require("../data/audio/Masei-3.mp3"),
    4: require("../data/audio/Masei-4.mp3"),
    5: require("../data/audio/Masei-5.mp3"),
    6: require("../data/audio/Masei-6.mp3"),
    7: require("../data/audio/Masei-7.mp3"),
    H: require("../data/audio/Masei-H.mp3"),
  },
  Devarim: {
    1: require("../data/audio/Devarim-1.mp3"),
    2: require("../data/audio/Devarim-2.mp3"),
    3: require("../data/audio/Devarim-3.mp3"),
    4: require("../data/audio/Devarim-4.mp3"),
    5: require("../data/audio/Devarim-5.mp3"),
    6: require("../data/audio/Devarim-6.mp3"),
    7: require("../data/audio/Devarim-7.mp3"),
    H: require("../data/audio/Devarim-H.mp3"),
  },
  Vaetchanan: {
    1: require("../data/audio/Vaethanan-1.mp3"),
    2: require("../data/audio/Vaethanan-2.mp3"),
    3: require("../data/audio/Vaethanan-3.mp3"),
    4: require("../data/audio/Vaethanan-4.mp3"),
    5: require("../data/audio/Vaethanan-5.mp3"),
    6: require("../data/audio/Vaethanan-6.mp3"),
    7: require("../data/audio/Vaethanan-7.mp3"),
    H: require("../data/audio/Vaethanan-H.mp3"),
  },
  Eikev: {
    1: require("../data/audio/Eikev-1.mp3"),
    2: require("../data/audio/Eikev-2.mp3"),
    3: require("../data/audio/Eikev-3.mp3"),
    4: require("../data/audio/Eikev-4.mp3"),
    5: require("../data/audio/Eikev-5.mp3"),
    6: require("../data/audio/Eikev-6.mp3"),
    7: require("../data/audio/Eikev-7.mp3"),
    H: require("../data/audio/Eikev-H.mp3"),
  },
  "Re'eh": {
    1: require("../data/audio/Reeh-1.mp3"),
    2: require("../data/audio/Reeh-2.mp3"),
    3: require("../data/audio/Reeh-3.mp3"),
    4: require("../data/audio/Reeh-4.mp3"),
    5: require("../data/audio/Reeh-5.mp3"),
    6: require("../data/audio/Reeh-6.mp3"),
    7: require("../data/audio/Reeh-7.mp3"),
    H: require("../data/audio/Reeh-H.mp3"),
  },
  Shoftim: {
    1: require("../data/audio/Shoftim-1.mp3"),
    2: require("../data/audio/Shoftim-2.mp3"),
    3: require("../data/audio/Shoftim-3.mp3"),
    4: require("../data/audio/Shoftim-4.mp3"),
    5: require("../data/audio/Shoftim-5.mp3"),
    6: require("../data/audio/Shoftim-6.mp3"),
    7: require("../data/audio/Shoftim-7.mp3"),
    H: require("../data/audio/Shoftim-H.mp3"),
  },
  "Ki Teitzei": {
    1: require("../data/audio/KiTeitzei-1.mp3"),
    2: require("../data/audio/KiTeitzei-2.mp3"),
    3: require("../data/audio/KiTeitzei-3.mp3"),
    4: require("../data/audio/KiTeitzei-4.mp3"),
    5: require("../data/audio/KiTeitzei-5.mp3"),
    6: require("../data/audio/KiTeitzei-6.mp3"),
    7: require("../data/audio/KiTeitzei-7.mp3"),
    H: require("../data/audio/KiTeitzei-H.mp3"),
  },
  "Ki Tavo": {
    1: require("../data/audio/KiTavo-1.mp3"),
    2: require("../data/audio/KiTavo-2.mp3"),
    3: require("../data/audio/KiTavo-3.mp3"),
    4: require("../data/audio/KiTavo-4.mp3"),
    5: require("../data/audio/KiTavo-5.mp3"),
    6: require("../data/audio/KiTavo-6.mp3"),
    7: require("../data/audio/KiTavo-7.mp3"),
    H: require("../data/audio/KiTavo-H.mp3"),
  },
  Nitzavim: {
    1: require("../data/audio/Nitzavim-1.mp3"),
    2: require("../data/audio/Nitzavim-2.mp3"),
    3: require("../data/audio/Nitzavim-3.mp3"),
    4: require("../data/audio/Nitzavim-4.mp3"),
    5: require("../data/audio/Nitzavim-5.mp3"),
    6: require("../data/audio/Nitzavim-6.mp3"),
    7: require("../data/audio/Nitzavim-7.mp3"),
    H: require("../data/audio/Nitzavim-H.mp3"),
  },
  Vayeilech: {
    1: require("../data/audio/Vayeilech-1.mp3"),
    2: require("../data/audio/Vayeilech-2.mp3"),
    3: require("../data/audio/Vayeilech-3.mp3"),
    4: require("../data/audio/Vayeilech-4.mp3"),
    5: require("../data/audio/Vayeilech-5.mp3"),
    6: require("../data/audio/Vayeilech-6.mp3"),
    7: require("../data/audio/Vayeilech-7.mp3"),
    H: require("../data/audio/Vayeilech-H.mp3"),
  },
  "Ha'azinu": {
    1: require("../data/audio/Haazinu-1.mp3"),
    2: require("../data/audio/Haazinu-2.mp3"),
    3: require("../data/audio/Haazinu-3.mp3"),
    4: require("../data/audio/Haazinu-4.mp3"),
    5: require("../data/audio/Haazinu-5.mp3"),
    6: require("../data/audio/Haazinu-6.mp3"),
    7: require("../data/audio/Haazinu-7.mp3"),
    H: require("../data/audio/Haazinu-H.mp3"),
  },
  "Vezot Haberakhah": {
    1: require("../data/audio/VezotHaberakhah-1.mp3"),
    2: require("../data/audio/VezotHaberakhah-2.mp3"),
    3: require("../data/audio/VezotHaberakhah-3.mp3"),
    4: require("../data/audio/VezotHaberakhah-4.mp3"),
    5: require("../data/audio/VezotHaberakhah-5.mp3"),
    6: require("../data/audio/VezotHaberakhah-6.mp3"),
    7: require("../data/audio/VezotHaberakhah-7.mp3"),
    H: require("../data/audio/VezotHaberakhah-H.mp3"),
  },
};

export const hebFont = "Taamey Frank Taamim Fix";
export const tikkunFont = "Stam Ashkenaz CLM";
export const fonts = {
  [hebFont]: require("../fonts/TaameyFrank-taamim-fix.ttf"),
  [tikkunFont]: require("../fonts/stamashkenazclm-webfont.ttf"),
};

export const tropeAudio: { [k in TropeType]: { [i: number]: any } } = {
  torah: {
    1: require("../data/trope/audio/torah-1.mp3"),
    2: require("../data/trope/audio/torah-2.mp3"),
    3: require("../data/trope/audio/torah-3.mp3"),
    4: require("../data/trope/audio/torah-4.mp3"),
    5: require("../data/trope/audio/torah-5.mp3"),
    6: require("../data/trope/audio/torah-6.mp3"),
    7: require("../data/trope/audio/torah-7.mp3"),
    8: require("../data/trope/audio/torah-8.mp3"),
    9: require("../data/trope/audio/torah-9.mp3"),
    10: require("../data/trope/audio/torah-10.mp3"),
    11: require("../data/trope/audio/torah-11.mp3"),
    12: require("../data/trope/audio/torah-12.mp3"),
  },
  haftarah: {
    1: require("../data/trope/audio/haftarah-1.mp3"),
    2: require("../data/trope/audio/haftarah-2.mp3"),
    3: require("../data/trope/audio/haftarah-3.mp3"),
    4: require("../data/trope/audio/haftarah-4.mp3"),
    5: require("../data/trope/audio/haftarah-5.mp3"),
    6: require("../data/trope/audio/haftarah-6.mp3"),
    7: require("../data/trope/audio/haftarah-7.mp3"),
    8: require("../data/trope/audio/haftarah-8.mp3"),
    9: require("../data/trope/audio/haftarah-9.mp3"),
    10: require("../data/trope/audio/haftarah-10.mp3"),
    11: require("../data/trope/audio/haftarah-11.mp3"),
    12: require("../data/trope/audio/haftarah-12.mp3"),
    13: require("../data/trope/audio/haftarah-13.mp3"),
    14: require("../data/trope/audio/haftarah-14.mp3"),
    15: require("../data/trope/audio/haftarah-15.mp3"),
  },
  esther: {
    1: require("../data/trope/audio/esther-1.mp3"),
    2: require("../data/trope/audio/esther-2.mp3"),
    3: require("../data/trope/audio/esther-3.mp3"),
    4: require("../data/trope/audio/esther-4.mp3"),
    5: require("../data/trope/audio/esther-5.mp3"),
    6: require("../data/trope/audio/esther-6.mp3"),
    7: require("../data/trope/audio/esther-7.mp3"),
    8: require("../data/trope/audio/esther-8.mp3"),
    9: require("../data/trope/audio/esther-9.mp3"),
    10: require("../data/trope/audio/esther-10.mp3"),
    11: require("../data/trope/audio/esther-11.mp3"),
    12: require("../data/trope/audio/esther-12.mp3"),
    13: require("../data/trope/audio/esther-13.mp3"),
    14: require("../data/trope/audio/esther-14.mp3"),
    15: require("../data/trope/audio/esther-15.mp3"),
    16: require("../data/trope/audio/esther-16.mp3"),
  },
  eicha: {
    1: require("../data/trope/audio/eicha-1.mp3"),
    2: require("../data/trope/audio/eicha-2.mp3"),
    3: require("../data/trope/audio/eicha-3.mp3"),
    4: require("../data/trope/audio/eicha-4.mp3"),
    5: require("../data/trope/audio/eicha-5.mp3"),
    6: require("../data/trope/audio/eicha-6.mp3"),
    7: require("../data/trope/audio/eicha-7.mp3"),
    8: require("../data/trope/audio/eicha-8.mp3"),
    9: require("../data/trope/audio/eicha-9.mp3"),
    10: require("../data/trope/audio/eicha-10.mp3"),
    11: require("../data/trope/audio/eicha-11.mp3"),
    12: require("../data/trope/audio/eicha-12.mp3"),
  },
  "3megillot": {
    1: require("../data/trope/audio/3megillot-1.mp3"),
    2: require("../data/trope/audio/3megillot-2.mp3"),
    3: require("../data/trope/audio/3megillot-3.mp3"),
    4: require("../data/trope/audio/3megillot-4.mp3"),
    5: require("../data/trope/audio/3megillot-5.mp3"),
    6: require("../data/trope/audio/3megillot-6.mp3"),
    7: require("../data/trope/audio/3megillot-7.mp3"),
    8: require("../data/trope/audio/3megillot-8.mp3"),
    9: require("../data/trope/audio/3megillot-9.mp3"),
    10: require("../data/trope/audio/3megillot-10.mp3"),
    11: require("../data/trope/audio/3megillot-11.mp3"),
    12: require("../data/trope/audio/3megillot-12.mp3"),
    13: require("../data/trope/audio/3megillot-13.mp3"),
    14: require("../data/trope/audio/3megillot-14.mp3"),
  },
  hhd: {
    1: require("../data/trope/audio/hhd-1.mp3"),
    2: require("../data/trope/audio/hhd-2.mp3"),
    3: require("../data/trope/audio/hhd-3.mp3"),
    4: require("../data/trope/audio/hhd-4.mp3"),
    5: require("../data/trope/audio/hhd-5.mp3"),
    6: require("../data/trope/audio/hhd-6.mp3"),
    7: require("../data/trope/audio/hhd-7.mp3"),
    8: require("../data/trope/audio/hhd-8.mp3"),
    9: require("../data/trope/audio/hhd-9.mp3"),
    10: require("../data/trope/audio/hhd-10.mp3"),
    11: require("../data/trope/audio/hhd-11.mp3"),
    12: require("../data/trope/audio/hhd-12.mp3"),
    13: require("../data/trope/audio/hhd-13.mp3"),
    14: require("../data/trope/audio/hhd-14.mp3"),
  },
};

export const tropeXml: { [k in TropeType]: { [i: number]: any } } = {
  torah: {
    1: require("../data/trope/text/torah-1.xml"),
    2: require("../data/trope/text/torah-2.xml"),
    3: require("../data/trope/text/torah-3.xml"),
    4: require("../data/trope/text/torah-4.xml"),
    5: require("../data/trope/text/torah-5.xml"),
    6: require("../data/trope/text/torah-6.xml"),
    7: require("../data/trope/text/torah-7.xml"),
    8: require("../data/trope/text/torah-8.xml"),
    9: require("../data/trope/text/torah-9.xml"),
    10: require("../data/trope/text/torah-10.xml"),
    11: require("../data/trope/text/torah-11.xml"),
    12: require("../data/trope/text/torah-12.xml"),
  },
  haftarah: {
    1: require("../data/trope/text/haftarah-1.xml"),
    2: require("../data/trope/text/haftarah-2.xml"),
    3: require("../data/trope/text/haftarah-3.xml"),
    4: require("../data/trope/text/haftarah-4.xml"),
    5: require("../data/trope/text/haftarah-5.xml"),
    6: require("../data/trope/text/haftarah-6.xml"),
    7: require("../data/trope/text/haftarah-7.xml"),
    8: require("../data/trope/text/haftarah-8.xml"),
    9: require("../data/trope/text/haftarah-9.xml"),
    10: require("../data/trope/text/haftarah-10.xml"),
    11: require("../data/trope/text/haftarah-11.xml"),
    12: require("../data/trope/text/haftarah-12.xml"),
    13: require("../data/trope/text/haftarah-13.xml"),
    14: require("../data/trope/text/haftarah-14.xml"),
    15: require("../data/trope/text/haftarah-15.xml"),
  },
  esther: {
    1: require("../data/trope/text/esther-1.xml"),
    2: require("../data/trope/text/esther-2.xml"),
    3: require("../data/trope/text/esther-3.xml"),
    4: require("../data/trope/text/esther-4.xml"),
    5: require("../data/trope/text/esther-5.xml"),
    6: require("../data/trope/text/esther-6.xml"),
    7: require("../data/trope/text/esther-7.xml"),
    8: require("../data/trope/text/esther-8.xml"),
    9: require("../data/trope/text/esther-9.xml"),
    10: require("../data/trope/text/esther-10.xml"),
    11: require("../data/trope/text/esther-11.xml"),
    12: require("../data/trope/text/esther-12.xml"),
    13: require("../data/trope/text/esther-13.xml"),
    14: require("../data/trope/text/esther-14.xml"),
    15: require("../data/trope/text/esther-15.xml"),
    16: require("../data/trope/text/esther-16.xml"),
  },
  eicha: {
    1: require("../data/trope/text/eicha-1.xml"),
    2: require("../data/trope/text/eicha-2.xml"),
    3: require("../data/trope/text/eicha-3.xml"),
    4: require("../data/trope/text/eicha-4.xml"),
    5: require("../data/trope/text/eicha-5.xml"),
    6: require("../data/trope/text/eicha-6.xml"),
    7: require("../data/trope/text/eicha-7.xml"),
    8: require("../data/trope/text/eicha-8.xml"),
    9: require("../data/trope/text/eicha-9.xml"),
    10: require("../data/trope/text/eicha-10.xml"),
    11: require("../data/trope/text/eicha-11.xml"),
    12: require("../data/trope/text/eicha-12.xml"),
  },
  "3megillot": {
    1: require("../data/trope/text/3megillot-1.xml"),
    2: require("../data/trope/text/3megillot-2.xml"),
    3: require("../data/trope/text/3megillot-3.xml"),
    4: require("../data/trope/text/3megillot-4.xml"),
    5: require("../data/trope/text/3megillot-5.xml"),
    6: require("../data/trope/text/3megillot-6.xml"),
    7: require("../data/trope/text/3megillot-7.xml"),
    8: require("../data/trope/text/3megillot-8.xml"),
    9: require("../data/trope/text/3megillot-9.xml"),
    10: require("../data/trope/text/3megillot-10.xml"),
    11: require("../data/trope/text/3megillot-11.xml"),
    12: require("../data/trope/text/3megillot-12.xml"),
    13: require("../data/trope/text/3megillot-13.xml"),
    14: require("../data/trope/text/3megillot-14.xml"),
  },
  hhd: {
    1: require("../data/trope/text/hhd-1.xml"),
    2: require("../data/trope/text/hhd-2.xml"),
    3: require("../data/trope/text/hhd-3.xml"),
    4: require("../data/trope/text/hhd-4.xml"),
    5: require("../data/trope/text/hhd-5.xml"),
    6: require("../data/trope/text/hhd-6.xml"),
    7: require("../data/trope/text/hhd-7.xml"),
    8: require("../data/trope/text/hhd-8.xml"),
    9: require("../data/trope/text/hhd-9.xml"),
    10: require("../data/trope/text/hhd-10.xml"),
    11: require("../data/trope/text/hhd-11.xml"),
    12: require("../data/trope/text/hhd-12.xml"),
    13: require("../data/trope/text/hhd-13.xml"),
    14: require("../data/trope/text/hhd-14.xml"),
  },
};

export const tropeLabels = {
  torah: require("../data/trope/labels/torah.json"),
  haftarah: require("../data/trope/labels/haftarah.json"),
  esther: require("../data/trope/labels/esther.json"),
  eicha: require("../data/trope/labels/eicha.json"),
  "3megillot": require("../data/trope/labels/3megillot.json"),
  hhd: require("../data/trope/labels/hhd.json"),
};
